In [1]:
!pip install numpy

In [2]:
!pip install numpy --upgrade

  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:
      Successfully uninstalled numpy-1.18.1


In [3]:
import numpy as np

In [4]:
array_one=np.array([1,2,3,4,5])

array_one

array([1, 2, 3, 4, 5])

In [5]:
type(array_one)

numpy.ndarray

In [6]:
num = [1,3,5,7,9,11]
array_two = np.array(num)

array_two

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
#array of matrices

In [8]:
array_of_zeros = np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
array_of_ones = np.ones((4,4))

array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
array_of_ones_int = np.ones((8,8) ,dtype = np.int32)

array_of_ones_int

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])