In [1]:
print("Bismillah")

Bismillah


In [ ]:
#arithematic operations

In [2]:
import numpy as np

In [18]:
a = np.array([10,10,10])
b = np.array([5,5,5])


In [7]:
a+b #addition


array([15, 15, 15])

In [8]:
a-b

array([5, 5, 5])

In [9]:
a*b

array([50, 50, 50])

In [10]:
a/b    #returns the divisor value

array([2., 2., 2.])

In [11]:
a % b   #returns the remainder value

array([0, 0, 0], dtype=int32)

In [ ]:
#modify an existing array

In [19]:
a *=3

a

array([30, 30, 30])

In [20]:
b +=a

b

array([35, 35, 35])

In [ ]:
#unary operators

In [21]:
ages = np.array([12,15,20,18,16,22,25,28])
ages

array([12, 15, 20, 18, 16, 22, 25, 28])

In [22]:
#to sumup the ages
ages.sum()

156

In [23]:
#to find the min age

ages.min()

12

In [24]:
#to find the max age

ages.max()

28

In [ ]:
#axis0 & axis1

In [27]:
num = np.arange(12).reshape(3,4)

num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
In 2D array axis0 --->col; axis1 --->row;

In [29]:
#sumup each column

num.sum(axis =0)

array([12, 15, 18, 21])

In [30]:
#sum up each row

num.sum(axis = 1)

array([ 6, 22, 38])

In [ ]:
#Intro to Statistical Function

In [31]:
test_score = np.array([25.5,18.02,10,45.65,48.5,35.10,40,24.98])

test_score

array([25.5 , 18.02, 10.  , 45.65, 48.5 , 35.1 , 40.  , 24.98])

In [32]:
#to print the mean of the score

print("Mean test score of the student :")
print(np.mean(test_score))

Mean test score of the student :
30.968749999999996


In [33]:
#to get the median of the score

print("Median test score of student: ")
print(np.median(test_score))

Median test score of student: 
30.3
