In [1]:
print("Bismillah")

Bismillah


In [ ]:
#Numpy Computation

In [3]:
import numpy as np

array_of_floats = np.arange(0,2,0.3)

array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
#2D array

In [5]:
array_2d = np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [6]:
array_2d.shape

(2, 3)

In [ ]:
#1D array

In [8]:
array_1d = np.arange(6)

array_1d

array([0, 1, 2, 3, 4, 5])

In [11]:
array_1d = np.array((0,1,2,3,4,5))

array_1d

array([0, 1, 2, 3, 4, 5])

In [ ]:
#2D array

In [12]:
array_nd = np.arange(6).reshape(3,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
array_nd = np.arange(8).reshape(4,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
#to print 3D array

In [19]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#1D

In [22]:
a = np.arange(6)

a

array([0, 1, 2, 3, 4, 5])

In [ ]:
#2d

In [25]:
b = np.arange(10).reshape(5,2)

b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])