In [1]:
print("Bismillah")

Bismillah


In [ ]:
#Statistical Function Of Numpy

In [5]:
import numpy as np

test_score = np.array([25.5,18.02,10,45.65,48.5,35.10,40,24.98])

test_score

array([25.5 , 18.02, 10.  , 45.65, 48.5 , 35.1 , 40.  , 24.98])

In [3]:
#to print the mean of the score

print("Mean test score of the student :")
print(np.mean(test_score))

Mean test score of the student :
30.968749999999996


In [4]:
#to get the median of the score

print("Median test score of student: ")
print(np.median(test_score))

Median test score of student: 
30.3


In [ ]:
Dataset: CSV(Comma Separated Value)

In [5]:
#open the csv file

salaries = np.genfromtxt('salary.csv',delimiter = ',')

salaries                #... in the output represents Elipses

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [6]:
salaries.shape

(1147,)

In [ ]:
req:To find the Mean,Median,Standard Deviation and Variance of salary

In [10]:
mean = np.mean(salaries)
median = np.median(salaries)
sd = np.std(salaries)
variance = np.var(salaries)

In [11]:
print("Mean = %i" %mean)
print("Median = %i" %median)
print("Standard Deviation = %i" %sd)
print("Variance = %i" %variance)

Mean = 55894
Median = 48000
Standard Deviation = 55170
Variance = 3043770333


In [ ]:
#looping through Numpy

In [12]:
a = np.arange(11)**2

a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
#looping through Multi-Dimensional arrays:

In [6]:
bank_cust =np.array([['Hameed','Jawa','Irfan','Isamth','Fareeza','Adnan'],[85,98,65,95,70,85],[78,85,72,80,72,78]])

bank_cust

array([['Hameed', 'Jawa', 'Irfan', 'Isamth', 'Fareeza', 'Adnan'],
       ['85', '98', '65', '95', '70', '85'],
       ['78', '85', '72', '80', '72', '78']], dtype='<U7')

In [28]:
for i in bank_cust:
    print('i =',i)

i = ['Hameed', 'Jawa', 'Irfan', 'Isamth', 'Fareeza', 'Adnan']
i = [85, 98, 65, 95, 70, 85]
i = [78, 85, 72, 80, 72, 78]


In [3]:
type(bank_cust)

list

In [ ]:
#split them entirely out of for loop:

In [7]:
for item in bank_cust.flatten():
    print(item)

Hameed
Jawa
Irfan
Isamth
Fareeza
Adnan
85
98
65
95
70
85
78
85
72
80
72
78
